axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [
    url(r'^$',views.home,name='index'),# 首页
    url(r'^home/$', views.home, name='home'),   # 首页
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$', views.cart, name='cart'),   # 购物车
    url(r'^mine/$', views.mine, name='mine'),   # 我的
    url(r'^registe/$',views.registe,name='registe'),# 注册
    url(r'^checkaccount/$', views.checkaccount, name='checkaccount'),  # 账号验证
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^checkphone/$',views.checkphone,name='checkphone'),
    url(r'^login/$',views.login,name='login'),
    url(r'^addcart/$',views.addcart,name='addcart'),
    url(r'^subcart/$', views.subcart, name='subcart'),  # 购物车减操作
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),
    url(r'changecartselect/$', views.changecartselect,name='changecartselect'),
    url(r'^generateorder/$',views.generateorder,name='generateorder'),
    url(r'^orderinfo/(\d+)/$',views.orderinfo,name='orderinfo'),

    url(r'^pay/$',views.pay,name='pay'),
    url(r'^notifyurl/$',views.notifyurl,name='notifyurl'),
    url(r'^returnurl/$',views.returnurl,name='returnurl'),
]

huangaxf/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('axf.urls',namespace='axf')),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
{#  CSS#}
    {% block extcss %}
    {% endblock %}

    <title>
{#      标题#}
        {% block title %}
        {% endblock %}
    </title>
</head>


<body>
{# 头部#}
{% block header %}
    <header>爱鲜蜂</header>
{% endblock %}

{# 主体内容#}
<div class="hidescroll">
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
</div>

{# 尾部#}
{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt> <span></span> </dt>
                <dd> 首页 </dd>
            </dl>
        </a>

        <a href="{% url 'axf:market' 104749 0 0%}" class="market">
            <dl>
                <dt> <span></span> </dt>
                <dd> 闪购超市 </dd>
            </dl>
        </a>

        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt> <span></span> </dt>
                <dd> 购物车 </dd>
            </dl>
        </a>

        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt> <span></span> </dt>
                <dd> 我的 </dd>
            </dl>
        </a>
    </footer>
{% endblock %}

</body>


<script src="{% static 'base/js/jquery.js' %}"></script>
<script src="{% static 'base/js/jquery.cookie.js' %}"></script>
<script src="{% static 'base/js/bootstrap.js' %}"></script>
<script src="{% static 'base/js/swiper.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>
{# JS#}
{% block extjs %}
{% endblock %}

</html>