axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [
    url(r'^$',views.home,name='index'),# 首页
    url(r'^home/$', views.home, name='home'),   # 首页
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$', views.cart, name='cart'),   # 购物车
    url(r'^mine/$', views.mine, name='mine'),   # 我的
    url(r'^registe/$',views.registe,name='registe'),# 注册
    url(r'^checkaccount/$', views.checkaccount, name='checkaccount'),  # 账号验证
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^checkphone/$',views.checkphone,name='checkphone'),
    url(r'^login/$',views.login,name='login'),
    url(r'^addcart/$',views.addcart,name='addcart'),
    url(r'^subcart/$', views.subcart, name='subcart'),  # 购物车减操作
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),
    url(r'changecartselect/$', views.changecartselect,name='changecartselect'),
    url(r'^generateorder/$',views.generateorder,name='generateorder'),
    url(r'^orderinfo/(\d+)/$',views.orderinfo,name='orderinfo'),

    url(r'^pay/$',views.pay,name='pay'),
    url(r'^notifyurl/$',views.notifyurl,name='notifyurl'),
    url(r'^returnurl/$',views.returnurl,name='returnurl'),
]

huangaxf/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('axf.urls',namespace='axf')),
]

templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

{% block title %}
    爱鲜蜂 | 登录
{% endblock %}

{% block content %}
    <div class="login">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>

        <form action="{% url 'axf:login' %}" method="post">
            {% csrf_token %}
            {#            账号#}
            <div class="form-group has-feedback" id="account">
                <div class="input-group">
                    <div class="input-group-addon">账号</div>
                    <input type="text" class="form-control" placeholder="数字、字母" name="account" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i>{{ accountErr }}</i>
            </div>

            {#            密码#}
            <div class="form-group" id="password">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="6~12位纯数字" name="password" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i>{{ passwdErr }}</i>
            </div>


{#            <input type="submit" id="subButton" value="登录">#}
            <div id="subButton" class="btn btn-default">
                登录
            </div>
        </form>
    </div>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}
{% block title %}
    爱鲜蜂 | 我的
{% endblock %}

{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <img src="{{ img }}" alt="">
            </div>
            <div class="user-content">
                <p>
                    <a href="{% url 'axf:login' %}">
                        <span class="glyphicon glyphicon-user"></span>
                        {{ name }}
                    </a>
                </p>
                <p>
                    <span class="glyphicon glyphicon-certificate "></span>
                    VIP:{{ rank | default:'暂无等级' }}
                </p>
                <a href="{% url 'axf:registe' %}" class="register">注册</a>
            </div>
        </div>
        <div class="collect">
            <span class="glyphicon glyphicon-pushpin "></span>
            <i>收藏</i>
        </div>
        <div class="other">
            <section class="my">
                <span>我的订单</span>
                <a href="#"> 查看订单 <b class="glyphicon glyphicon-chevron-right"></b> </a>
            </section>
             <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt> <b class="glyphicon glyphicon-shopping-cart"></b> </dt>
                                <dd> 待付款 </dd>
                                <span class="badge" style="color:white;background: red">{{ waitpay }}</span>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt> <b class="glyphicon glyphicon-thumbs-up"></b> </dt>
                                <dd> 待收货 </dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt> <b class="glyphicon glyphicon-bell
glyphicon"></b> </dt>
                                <dd> 待评价 </dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt> <b class=" glyphicon glyphicon-bullhorn"></b> </dt>
                                <dd> 退款 </dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>
            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt> <b class="glyphicon glyphicon-compressed"></b> </dt>
                                <dd> 优惠券 </dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt> <b class="glyphicon glyphicon-earphone"></b> </dt>
                                <dd> 收货地址 </dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt> <b class="glyphicon glyphicon-phone-alt"></b> </dt>
                                <dd> 客户反馈 </dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt> <b class="glyphicon glyphicon-stats"></b> </dt>
                                <dd> 关于我们 </dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>
            {% if isLogin %}
                <section class="quit">
                    <a href="/logout/">退出</a>
                </section>
            {% endif %}

        </div>
    </div>
{% endblock %}

templates/mine/registe.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/registe.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/registerAxf.js' %}"></script>
{% endblock %}
 {% block title %}
    爱鲜蜂 | 注册
{% endblock %}
 {% block content %}
    <div class="register">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>
         <form action="{% url 'axf:registe' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {#            账号#}
            <div class="form-group has-feedback" id="account">
                <div class="input-group">
                    <div class="input-group-addon">账号</div>
                    <input type="text" class="form-control" placeholder="数字、字母" name="account" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
             {#            密码#}
            <div class="form-group" id="password">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="6~12位纯数字" name="password" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
             {#            确认密码#}
            <div class="form-group" id="passwd">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="6~12位" name="passwd" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
             {#            名字#}
            <div class="form-group" id="name">
                <div class="input-group">
                    <div class="input-group-addon">名字</div>
                    <input type="text" class="form-control" placeholder="名字" name="name" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
             {#            手机号#}
            <div class="form-group" id="phone">
                <div class="input-group">
                    <div class="input-group-addon">手机</div>
                    <input type="text" class="form-control" placeholder="11位" name="phone" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
             {#            地址#}
            <div class="form-group" id="addr">
                <div class="input-group">
                    <div class="input-group-addon">地址</div>
                    <input type="text" class="form-control" placeholder="收货地址(默认选项)" name="addr" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
            </div>
             {#            头像#}
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">头像</div>
                    <input type="file" name="icon" required="required">
                </div>
            </div>
             <input type="submit" id="subButton" value="注册">
        </form>
    </div>
{% endblock %}